site_name: Binokula Documentation
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
    - 'https://unpkg.com/mermaid@7.1.2/dist/mermaid.css'
extra_javascript:
    - 'https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js'

theme:
    name: material
    custom_dir: theme
    logo: 'images/logo.png'
nav:
    - 'Introduction': 'index.md'
    - 'Admin Guide': 'admin-guide.md'
    - 'Developer Guide': 'developer-guide.md'
    - 'User Guide': 'user-guide.md'
    - 'Release Notes': 'release-notes.md'
    - 'FAQ': 'faq.md'
    